/*
 * Customer Journey as a Service (CJaaS)
 * Something amazing, something special - the Customer Journey as a Service (CJaaS) is a core data layer to enable Journeys across products built upon serverless multi-cloud architecture, to be available as a SaaS service for applications inside and outside of Cisco. [**Cisco Experimental - Not For Production Use**]
 *
 * OpenAPI spec version: 0.5.0
 * Contact: cjaas-earlyaccess@cisco.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProfileViewBuilderTemplateAttribute;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ProfileAttributeView
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-10T15:46:40.647328-07:00[America/Denver]")
public class ProfileAttributeView {
  @SerializedName("queryTemplate")
  private ProfileViewBuilderTemplateAttribute queryTemplate = null;

  @SerializedName("result")
  private String result = null;

  public ProfileAttributeView queryTemplate(ProfileViewBuilderTemplateAttribute queryTemplate) {
    this.queryTemplate = queryTemplate;
    return this;
  }

   /**
   * Get queryTemplate
   * @return queryTemplate
  **/
  @Schema(description = "")
  public ProfileViewBuilderTemplateAttribute getQueryTemplate() {
    return queryTemplate;
  }

  public void setQueryTemplate(ProfileViewBuilderTemplateAttribute queryTemplate) {
    this.queryTemplate = queryTemplate;
  }

  public ProfileAttributeView result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(description = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileAttributeView profileAttributeView = (ProfileAttributeView) o;
    return Objects.equals(this.queryTemplate, profileAttributeView.queryTemplate) &&
        Objects.equals(this.result, profileAttributeView.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryTemplate, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileAttributeView {\n");
    
    sb.append("    queryTemplate: ").append(toIndentedString(queryTemplate)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
