# coding: utf-8

"""
    Customer Journey as a Service (CJaaS)

    Something amazing, something special - the Customer Journey as a Service (CJaaS) is a core data layer to enable Journeys across products built upon serverless multi-cloud architecture, to be available as a SaaS service for applications inside and outside of Cisco. [**Cisco Experimental - Not For Production Use**]  # noqa: E501

    OpenAPI spec version: 0.5.0
    Contact: cjaas-earlyaccess@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cloud_event import CloudEvent  # noqa: E501
from swagger_client.rest import ApiException


class TestCloudEvent(unittest.TestCase):
    """CloudEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudEvent(self):
        """Test CloudEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cloud_event.CloudEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
