# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HttpErrorResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'ErrorObject',
        'tracking_id': 'str'
    }

    attribute_map = {
        'error': 'error',
        'tracking_id': 'trackingId'
    }

    def __init__(self, error=None, tracking_id=None):  # noqa: E501
        """HttpErrorResponse - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._tracking_id = None
        self.discriminator = None
        if error is not None:
            self.error = error
        if tracking_id is not None:
            self.tracking_id = tracking_id

    @property
    def error(self):
        """Gets the error of this HttpErrorResponse.  # noqa: E501


        :return: The error of this HttpErrorResponse.  # noqa: E501
        :rtype: ErrorObject
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this HttpErrorResponse.


        :param error: The error of this HttpErrorResponse.  # noqa: E501
        :type: ErrorObject
        """

        self._error = error

    @property
    def tracking_id(self):
        """Gets the tracking_id of this HttpErrorResponse.  # noqa: E501


        :return: The tracking_id of this HttpErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._tracking_id

    @tracking_id.setter
    def tracking_id(self, tracking_id):
        """Sets the tracking_id of this HttpErrorResponse.


        :param tracking_id: The tracking_id of this HttpErrorResponse.  # noqa: E501
        :type: str
        """

        self._tracking_id = tracking_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HttpErrorResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HttpErrorResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
