# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProfileAttributeView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query_template': 'ProfileViewBuilderTemplateAttribute',
        'result': 'str',
        'journey_events': 'str'
    }

    attribute_map = {
        'query_template': 'queryTemplate',
        'result': 'result',
        'journey_events': 'journeyEvents'
    }

    def __init__(self, query_template=None, result=None, journey_events=None):  # noqa: E501
        """ProfileAttributeView - a model defined in Swagger"""  # noqa: E501
        self._query_template = None
        self._result = None
        self._journey_events = None
        self.discriminator = None
        if query_template is not None:
            self.query_template = query_template
        if result is not None:
            self.result = result
        if journey_events is not None:
            self.journey_events = journey_events

    @property
    def query_template(self):
        """Gets the query_template of this ProfileAttributeView.  # noqa: E501


        :return: The query_template of this ProfileAttributeView.  # noqa: E501
        :rtype: ProfileViewBuilderTemplateAttribute
        """
        return self._query_template

    @query_template.setter
    def query_template(self, query_template):
        """Sets the query_template of this ProfileAttributeView.


        :param query_template: The query_template of this ProfileAttributeView.  # noqa: E501
        :type: ProfileViewBuilderTemplateAttribute
        """

        self._query_template = query_template

    @property
    def result(self):
        """Gets the result of this ProfileAttributeView.  # noqa: E501


        :return: The result of this ProfileAttributeView.  # noqa: E501
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this ProfileAttributeView.


        :param result: The result of this ProfileAttributeView.  # noqa: E501
        :type: str
        """

        self._result = result

    @property
    def journey_events(self):
        """Gets the journey_events of this ProfileAttributeView.  # noqa: E501


        :return: The journey_events of this ProfileAttributeView.  # noqa: E501
        :rtype: str
        """
        return self._journey_events

    @journey_events.setter
    def journey_events(self, journey_events):
        """Sets the journey_events of this ProfileAttributeView.


        :param journey_events: The journey_events of this ProfileAttributeView.  # noqa: E501
        :type: str
        """

        self._journey_events = journey_events

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProfileAttributeView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProfileAttributeView):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
