# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProfileViewTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'namespace': 'str',
        'organization': 'str',
        'attributes': 'list[ProfileViewTemplateAttribute]'
    }

    attribute_map = {
        'name': 'name',
        'namespace': 'namespace',
        'organization': 'organization',
        'attributes': 'attributes'
    }

    def __init__(self, name=None, namespace=None, organization=None, attributes=None):  # noqa: E501
        """ProfileViewTemplate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._namespace = None
        self._organization = None
        self._attributes = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if namespace is not None:
            self.namespace = namespace
        if organization is not None:
            self.organization = organization
        if attributes is not None:
            self.attributes = attributes

    @property
    def name(self):
        """Gets the name of this ProfileViewTemplate.  # noqa: E501

        Name of the view to be built.  # noqa: E501

        :return: The name of this ProfileViewTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProfileViewTemplate.

        Name of the view to be built.  # noqa: E501

        :param name: The name of this ProfileViewTemplate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this ProfileViewTemplate.  # noqa: E501

        CJaaS Namespace to which this template belongs.  # noqa: E501

        :return: The namespace of this ProfileViewTemplate.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this ProfileViewTemplate.

        CJaaS Namespace to which this template belongs.  # noqa: E501

        :param namespace: The namespace of this ProfileViewTemplate.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def organization(self):
        """Gets the organization of this ProfileViewTemplate.  # noqa: E501

        CJaaS Organization to which this template belongs.  # noqa: E501

        :return: The organization of this ProfileViewTemplate.  # noqa: E501
        :rtype: str
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this ProfileViewTemplate.

        CJaaS Organization to which this template belongs.  # noqa: E501

        :param organization: The organization of this ProfileViewTemplate.  # noqa: E501
        :type: str
        """

        self._organization = organization

    @property
    def attributes(self):
        """Gets the attributes of this ProfileViewTemplate.  # noqa: E501

        List of attributes to build the view.  # noqa: E501

        :return: The attributes of this ProfileViewTemplate.  # noqa: E501
        :rtype: list[ProfileViewTemplateAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ProfileViewTemplate.

        List of attributes to build the view.  # noqa: E501

        :param attributes: The attributes of this ProfileViewTemplate.  # noqa: E501
        :type: list[ProfileViewTemplateAttribute]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProfileViewTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProfileViewTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
