/*
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * IdentityAliasesRequestBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-06T10:05:17.823-05:00[America/Chicago]")
public class IdentityAliasesRequestBody {
  @SerializedName("aliases")
  private List<String> aliases = null;

  public IdentityAliasesRequestBody aliases(List<String> aliases) {
    this.aliases = aliases;
    return this;
  }

  public IdentityAliasesRequestBody addAliasesItem(String aliasesItem) {
    if (this.aliases == null) {
      this.aliases = new ArrayList<String>();
    }
    this.aliases.add(aliasesItem);
    return this;
  }

   /**
   * List of Aliases value to associate an identity with. This identity&#x27;s events can be looked up with any of the given aliases. It is a override operation. Existing set of aliases will be overridden with the new set.
   * @return aliases
  **/
  @Schema(description = "List of Aliases value to associate an identity with. This identity's events can be looked up with any of the given aliases. It is a override operation. Existing set of aliases will be overridden with the new set.")
  public List<String> getAliases() {
    return aliases;
  }

  public void setAliases(List<String> aliases) {
    this.aliases = aliases;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityAliasesRequestBody identityAliasesRequestBody = (IdentityAliasesRequestBody) o;
    return Objects.equals(this.aliases, identityAliasesRequestBody.aliases);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aliases);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityAliasesRequestBody {\n");
    
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
