# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app(self):
        """Test case for create_app

        Create App  # noqa: E501
        """
        pass

    def test_delete_app(self):
        """Test case for delete_app

        Delete App  # noqa: E501
        """
        pass

    def test_list_apps(self):
        """Test case for list_apps

        List Apps  # noqa: E501
        """
        pass

    def test_rotate_app_key(self):
        """Test case for rotate_app_key

        Rotate App Key  # noqa: E501
        """
        pass

    def test_update_app_attributes(self):
        """Test case for update_app_attributes

        Update App Attributes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
