# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.journey_api import JourneyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJourneyApi(unittest.TestCase):
    """JourneyApi unit test stubs"""

    def setUp(self):
        self.api = JourneyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_or_update_an_alias(self):
        """Test case for create_or_update_an_alias

        Create or Update an Alias  # noqa: E501
        """
        pass

    def test_delete_identity(self):
        """Test case for delete_identity

        Delete Identity  # noqa: E501
        """
        pass

    def test_delete_identity_aliases(self):
        """Test case for delete_identity_aliases

        Delete Identity Aliases  # noqa: E501
        """
        pass

    def test_get_identity_by_id(self):
        """Test case for get_identity_by_id

        Get Identity By Id  # noqa: E501
        """
        pass

    def test_list_identities(self):
        """Test case for list_identities

        List Identities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
