/*
 * Customer Journey as a Service (CJaaS)
 *
 * Something amazing, something special - the Customer Journey as a Service (CJaaS) is a core data layer to enable Journeys across products built upon serverless multi-cloud architecture, to be available as a SaaS service for applications inside and outside of Cisco. [**Cisco Experimental - Not For Production Use**]
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: cjaas-earlyaccess@cisco.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountSettings {
    #[serde(rename = "dataRetentionDays", skip_serializing_if = "Option::is_none")]
    pub data_retention_days: Option<i32>,
    #[serde(rename = "destinationSubscriptions", skip_serializing_if = "Option::is_none")]
    pub destination_subscriptions: Option<Vec<String>>,
    #[serde(rename = "webexTokenIssuer", skip_serializing_if = "Option::is_none")]
    pub webex_token_issuer: Option<String>,
    #[serde(rename = "webexTokenIssuerSecret", skip_serializing_if = "Option::is_none")]
    pub webex_token_issuer_secret: Option<String>,
}

impl AccountSettings {
    pub fn new() -> AccountSettings {
        AccountSettings {
            data_retention_days: None,
            destination_subscriptions: None,
            webex_token_issuer: None,
            webex_token_issuer_secret: None,
        }
    }
}


