/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Action {
    /// Action Type
    #[serde(rename = "actionType", skip_serializing_if = "Option::is_none")]
    pub action_type: Option<ActionType>,
    /// Action Config
    #[serde(rename = "actionConfig", skip_serializing_if = "Option::is_none")]
    pub action_config: Option<serde_json::Value>,
}

impl Action {
    pub fn new() -> Action {
        Action {
            action_type: None,
            action_config: None,
        }
    }
}

/// Action Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActionType {
    #[serde(rename = "1")]
    _1,
    #[serde(rename = "2")]
    _2,
    #[serde(rename = "3")]
    _3,
    #[serde(rename = "4")]
    _4,
    #[serde(rename = "5")]
    _5,
}

