/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudEvent {
    /// The Spec Version for this event.
    #[serde(rename = "specVersion", skip_serializing_if = "Option::is_none")]
    pub spec_version: Option<String>,
    /// what is the source of this event.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// source generated GUID that uniquely identifies this event.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// User ID for the person to whose journey this event will be linked to.
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<String>,
    /// if any other user id was used in the previous context. this will serve as alias going forward.
    #[serde(rename = "previously", skip_serializing_if = "Option::is_none")]
    pub previously: Option<String>,
    /// type of event.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Embedded JSON string. Could contain any valid JSON document.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// Content Type of Data.
    #[serde(rename = "dataContentType", skip_serializing_if = "Option::is_none")]
    pub data_content_type: Option<String>,
    /// timestamp at source system at time of publishing.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl CloudEvent {
    pub fn new() -> CloudEvent {
        CloudEvent {
            spec_version: None,
            source: None,
            id: None,
            person: None,
            previously: None,
            _type: None,
            data: None,
            data_content_type: None,
            time: None,
        }
    }
}


