/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpGenericListObjectResponseProfileViewTemplate {
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::HttpResponseMeta>>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::ProfileViewTemplate>>,
}

impl HttpGenericListObjectResponseProfileViewTemplate {
    pub fn new() -> HttpGenericListObjectResponseProfileViewTemplate {
        HttpGenericListObjectResponseProfileViewTemplate {
            meta: None,
            data: None,
        }
    }
}


