/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifiedCloudEvent {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "dataContentType", skip_serializing_if = "Option::is_none")]
    pub data_content_type: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<String>,
    #[serde(rename = "previously", skip_serializing_if = "Option::is_none")]
    pub previously: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "specVersion", skip_serializing_if = "Option::is_none")]
    pub spec_version: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl ModifiedCloudEvent {
    pub fn new() -> ModifiedCloudEvent {
        ModifiedCloudEvent {
            data: None,
            data_content_type: None,
            id: None,
            person: None,
            previously: None,
            source: None,
            spec_version: None,
            time: None,
            _type: None,
        }
    }
}


