/*
 * Customer Journey as a Service (CJaaS)
 *
 * Something amazing, something special - the Customer Journey as a Service (CJaaS) is a core data layer to enable Journeys across products built upon serverless multi-cloud architecture, to be available as a SaaS service for applications inside and outside of Cisco. [**Cisco Experimental - Not For Production Use**]
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: cjaas-earlyaccess@cisco.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileViewBuilderTemplate {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "datapointCount", skip_serializing_if = "Option::is_none")]
    pub datapoint_count: Option<i32>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::ProfileViewBuilderTemplateAttribute>>,
}

impl ProfileViewBuilderTemplate {
    pub fn new() -> ProfileViewBuilderTemplate {
        ProfileViewBuilderTemplate {
            name: None,
            datapoint_count: None,
            attributes: None,
        }
    }
}


