/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileViewTemplate {
    /// Name of the view to be built.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// CJaaS Namespace to which this template belongs.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// CJaaS Organization to which this template belongs.
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    /// List of attributes to build the view.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::ProfileViewTemplateAttribute>>,
}

impl ProfileViewTemplate {
    pub fn new() -> ProfileViewTemplate {
        ProfileViewTemplate {
            name: None,
            namespace: None,
            organization: None,
            attributes: None,
        }
    }
}


