/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileViewTemplateCreateModel {
    /// Identifier for the view to be built.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Attributes to be used for building the profile view.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::ProfileViewTemplateAttribute>>,
}

impl ProfileViewTemplateCreateModel {
    pub fn new() -> ProfileViewTemplateCreateModel {
        ProfileViewTemplateCreateModel {
            id: None,
            attributes: None,
        }
    }
}


