/*
 * Azure Functions OpenAPI Extension
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileViewBuilderTemplate {
    /// Name of the view to be built.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Number of Journey events to be considered, in order to build the view.
    #[serde(rename = "datapointCount", skip_serializing_if = "Option::is_none")]
    pub datapoint_count: Option<i32>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::ProfileViewBuilderTemplateAttribute>>,
}

impl ProfileViewBuilderTemplate {
    pub fn new() -> ProfileViewBuilderTemplate {
        ProfileViewBuilderTemplate {
            name: None,
            datapoint_count: None,
            attributes: None,
        }
    }
}


