/*
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DataMessage;
import io.swagger.client.model.HttpResponseMeta;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * HttpSimpleMessageObjectResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-06T08:57:46.449-05:00[America/Chicago]")
public class HttpSimpleMessageObjectResponse {
  @SerializedName("meta")
  private HttpResponseMeta meta = null;

  @SerializedName("data")
  private DataMessage data = null;

  public HttpSimpleMessageObjectResponse meta(HttpResponseMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @Schema(description = "")
  public HttpResponseMeta getMeta() {
    return meta;
  }

  public void setMeta(HttpResponseMeta meta) {
    this.meta = meta;
  }

  public HttpSimpleMessageObjectResponse data(DataMessage data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public DataMessage getData() {
    return data;
  }

  public void setData(DataMessage data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpSimpleMessageObjectResponse httpSimpleMessageObjectResponse = (HttpSimpleMessageObjectResponse) o;
    return Objects.equals(this.meta, httpSimpleMessageObjectResponse.meta) &&
        Objects.equals(this.data, httpSimpleMessageObjectResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpSimpleMessageObjectResponse {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
