/*
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.HttpReport;
import io.swagger.client.model.HttpResponseMeta;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * HttpReportObjectResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-06T08:57:46.449-05:00[America/Chicago]")
public class HttpReportObjectResponse {
  @SerializedName("meta")
  private HttpResponseMeta meta = null;

  @SerializedName("report")
  private HttpReport report = null;

  public HttpReportObjectResponse meta(HttpResponseMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @Schema(description = "")
  public HttpResponseMeta getMeta() {
    return meta;
  }

  public void setMeta(HttpResponseMeta meta) {
    this.meta = meta;
  }

  public HttpReportObjectResponse report(HttpReport report) {
    this.report = report;
    return this;
  }

   /**
   * Get report
   * @return report
  **/
  @Schema(description = "")
  public HttpReport getReport() {
    return report;
  }

  public void setReport(HttpReport report) {
    this.report = report;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpReportObjectResponse httpReportObjectResponse = (HttpReportObjectResponse) o;
    return Objects.equals(this.meta, httpReportObjectResponse.meta) &&
        Objects.equals(this.report, httpReportObjectResponse.report);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, report);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpReportObjectResponse {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    report: ").append(toIndentedString(report)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
