/*
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProfileAttributeView;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * ProfileViewQueryResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-06T08:57:46.449-05:00[America/Chicago]")
public class ProfileViewQueryResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("generatedAt")
  private OffsetDateTime generatedAt = null;

  @SerializedName("attributeView")
  private List<ProfileAttributeView> attributeView = null;

  public ProfileViewQueryResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProfileViewQueryResponse customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @Schema(description = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public ProfileViewQueryResponse generatedAt(OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
    return this;
  }

   /**
   * Get generatedAt
   * @return generatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getGeneratedAt() {
    return generatedAt;
  }

  public void setGeneratedAt(OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
  }

  public ProfileViewQueryResponse attributeView(List<ProfileAttributeView> attributeView) {
    this.attributeView = attributeView;
    return this;
  }

  public ProfileViewQueryResponse addAttributeViewItem(ProfileAttributeView attributeViewItem) {
    if (this.attributeView == null) {
      this.attributeView = new ArrayList<ProfileAttributeView>();
    }
    this.attributeView.add(attributeViewItem);
    return this;
  }

   /**
   * Get attributeView
   * @return attributeView
  **/
  @Schema(description = "")
  public List<ProfileAttributeView> getAttributeView() {
    return attributeView;
  }

  public void setAttributeView(List<ProfileAttributeView> attributeView) {
    this.attributeView = attributeView;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileViewQueryResponse profileViewQueryResponse = (ProfileViewQueryResponse) o;
    return Objects.equals(this.name, profileViewQueryResponse.name) &&
        Objects.equals(this.customerId, profileViewQueryResponse.customerId) &&
        Objects.equals(this.generatedAt, profileViewQueryResponse.generatedAt) &&
        Objects.equals(this.attributeView, profileViewQueryResponse.attributeView);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, customerId, generatedAt, attributeView);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileViewQueryResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    generatedAt: ").append(toIndentedString(generatedAt)).append("\n");
    sb.append("    attributeView: ").append(toIndentedString(attributeView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
