/*
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProfileViewTemplateAttribute;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ProfileViewTemplate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-06T08:57:46.449-05:00[America/Chicago]")
public class ProfileViewTemplate {
  @SerializedName("name")
  private String name = null;

  @SerializedName("namespace")
  private String namespace = null;

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("attributes")
  private List<ProfileViewTemplateAttribute> attributes = null;

  public ProfileViewTemplate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the view to be built.
   * @return name
  **/
  @Schema(description = "Name of the view to be built.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProfileViewTemplate namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * CJaaS Namespace to which this template belongs.
   * @return namespace
  **/
  @Schema(description = "CJaaS Namespace to which this template belongs.")
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  public ProfileViewTemplate organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * CJaaS Organization to which this template belongs.
   * @return organization
  **/
  @Schema(description = "CJaaS Organization to which this template belongs.")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public ProfileViewTemplate attributes(List<ProfileViewTemplateAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ProfileViewTemplate addAttributesItem(ProfileViewTemplateAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<ProfileViewTemplateAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * List of attributes to build the view.
   * @return attributes
  **/
  @Schema(description = "List of attributes to build the view.")
  public List<ProfileViewTemplateAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<ProfileViewTemplateAttribute> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileViewTemplate profileViewTemplate = (ProfileViewTemplate) o;
    return Objects.equals(this.name, profileViewTemplate.name) &&
        Objects.equals(this.namespace, profileViewTemplate.namespace) &&
        Objects.equals(this.organization, profileViewTemplate.organization) &&
        Objects.equals(this.attributes, profileViewTemplate.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, namespace, organization, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileViewTemplate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
