/*
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ProfileViewBuilderTemplateAttribute;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ProfileAttributeView
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-06T08:57:46.449-05:00[America/Chicago]")
public class ProfileAttributeView {
  @SerializedName("queryTemplate")
  private ProfileViewBuilderTemplateAttribute queryTemplate = null;

  @SerializedName("result")
  private String result = null;

  @SerializedName("journeyEvents")
  private String journeyEvents = null;

  public ProfileAttributeView queryTemplate(ProfileViewBuilderTemplateAttribute queryTemplate) {
    this.queryTemplate = queryTemplate;
    return this;
  }

   /**
   * Get queryTemplate
   * @return queryTemplate
  **/
  @Schema(description = "")
  public ProfileViewBuilderTemplateAttribute getQueryTemplate() {
    return queryTemplate;
  }

  public void setQueryTemplate(ProfileViewBuilderTemplateAttribute queryTemplate) {
    this.queryTemplate = queryTemplate;
  }

  public ProfileAttributeView result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(description = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public ProfileAttributeView journeyEvents(String journeyEvents) {
    this.journeyEvents = journeyEvents;
    return this;
  }

   /**
   * Get journeyEvents
   * @return journeyEvents
  **/
  @Schema(description = "")
  public String getJourneyEvents() {
    return journeyEvents;
  }

  public void setJourneyEvents(String journeyEvents) {
    this.journeyEvents = journeyEvents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileAttributeView profileAttributeView = (ProfileAttributeView) o;
    return Objects.equals(this.queryTemplate, profileAttributeView.queryTemplate) &&
        Objects.equals(this.result, profileAttributeView.result) &&
        Objects.equals(this.journeyEvents, profileAttributeView.journeyEvents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryTemplate, result, journeyEvents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileAttributeView {\n");
    
    sb.append("    queryTemplate: ").append(toIndentedString(queryTemplate)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    journeyEvents: ").append(toIndentedString(journeyEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
