# coding: utf-8

# flake8: noqa
"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.apps_document_swagger import AppsDocumentSwagger
from swagger_client.models.create_app import CreateApp
from swagger_client.models.data_message import DataMessage
from swagger_client.models.error_object import ErrorObject
from swagger_client.models.http_error_response import HttpErrorResponse
from swagger_client.models.http_generic_list_object_response_apps_document_swagger import HttpGenericListObjectResponseAppsDocumentSwagger
from swagger_client.models.http_generic_list_object_response_identity import HttpGenericListObjectResponseIdentity
from swagger_client.models.http_generic_object_response_create_app import HttpGenericObjectResponseCreateApp
from swagger_client.models.http_generic_object_response_identity_by_id import HttpGenericObjectResponseIdentityById
from swagger_client.models.http_response_meta import HttpResponseMeta
from swagger_client.models.http_simple_message_object_response import HttpSimpleMessageObjectResponse
from swagger_client.models.identity import Identity
from swagger_client.models.identity_aliases_request_body import IdentityAliasesRequestBody
from swagger_client.models.identity_by_id import IdentityById
from swagger_client.models.message_object import MessageObject
