# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdentityAliasesRequestBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aliases': 'list[str]'
    }

    attribute_map = {
        'aliases': 'aliases'
    }

    def __init__(self, aliases=None):  # noqa: E501
        """IdentityAliasesRequestBody - a model defined in Swagger"""  # noqa: E501
        self._aliases = None
        self.discriminator = None
        if aliases is not None:
            self.aliases = aliases

    @property
    def aliases(self):
        """Gets the aliases of this IdentityAliasesRequestBody.  # noqa: E501

        List of Aliases value to associate an identity with. This identity's events can be looked up with any of the given aliases. It is a override operation. Existing set of aliases will be overridden with the new set.  # noqa: E501

        :return: The aliases of this IdentityAliasesRequestBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this IdentityAliasesRequestBody.

        List of Aliases value to associate an identity with. This identity's events can be looked up with any of the given aliases. It is a override operation. Existing set of aliases will be overridden with the new set.  # noqa: E501

        :param aliases: The aliases of this IdentityAliasesRequestBody.  # noqa: E501
        :type: list[str]
        """

        self._aliases = aliases

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdentityAliasesRequestBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdentityAliasesRequestBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
