# coding: utf-8

"""
    Customer Journey as a Service (CJaaS)

    Something amazing, something special - the Customer Journey as a Service (CJaaS) is a core data layer to enable Journeys across products built upon serverless multi-cloud architecture, to be available as a SaaS service for applications inside and outside of Cisco. [**Cisco Experimental - Not For Production Use**]  # noqa: E501

    OpenAPI spec version: 0.5.0
    Contact: cjaas-earlyaccess@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProfileViewBuilderTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'datapoint_count': 'int',
        'attributes': 'list[ProfileViewBuilderTemplateAttribute]'
    }

    attribute_map = {
        'name': 'name',
        'datapoint_count': 'datapointCount',
        'attributes': 'attributes'
    }

    def __init__(self, name=None, datapoint_count=None, attributes=None):  # noqa: E501
        """ProfileViewBuilderTemplate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._datapoint_count = None
        self._attributes = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if datapoint_count is not None:
            self.datapoint_count = datapoint_count
        if attributes is not None:
            self.attributes = attributes

    @property
    def name(self):
        """Gets the name of this ProfileViewBuilderTemplate.  # noqa: E501


        :return: The name of this ProfileViewBuilderTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProfileViewBuilderTemplate.


        :param name: The name of this ProfileViewBuilderTemplate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def datapoint_count(self):
        """Gets the datapoint_count of this ProfileViewBuilderTemplate.  # noqa: E501


        :return: The datapoint_count of this ProfileViewBuilderTemplate.  # noqa: E501
        :rtype: int
        """
        return self._datapoint_count

    @datapoint_count.setter
    def datapoint_count(self, datapoint_count):
        """Sets the datapoint_count of this ProfileViewBuilderTemplate.


        :param datapoint_count: The datapoint_count of this ProfileViewBuilderTemplate.  # noqa: E501
        :type: int
        """

        self._datapoint_count = datapoint_count

    @property
    def attributes(self):
        """Gets the attributes of this ProfileViewBuilderTemplate.  # noqa: E501


        :return: The attributes of this ProfileViewBuilderTemplate.  # noqa: E501
        :rtype: list[ProfileViewBuilderTemplateAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ProfileViewBuilderTemplate.


        :param attributes: The attributes of this ProfileViewBuilderTemplate.  # noqa: E501
        :type: list[ProfileViewBuilderTemplateAttribute]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProfileViewBuilderTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProfileViewBuilderTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
