# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.journey_api import JourneyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJourneyApi(unittest.TestCase):
    """JourneyApi unit test stubs"""

    def setUp(self):
        self.api = JourneyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_journey_action(self):
        """Test case for create_journey_action

        Create/Replace Journey Action.  # noqa: E501
        """
        pass

    def test_create_profile_view_template(self):
        """Test case for create_profile_view_template

        Create Profile View Template  # noqa: E501
        """
        pass

    def test_create_view(self):
        """Test case for create_view

        Starts job to generate Progressive Profile View for a person.  # noqa: E501
        """
        pass

    def test_delete_journey_action(self):
        """Test case for delete_journey_action

        Soft delete Journey Action.  # noqa: E501
        """
        pass

    def test_delete_profile_view_template(self):
        """Test case for delete_profile_view_template

        Delete Profile View Template  # noqa: E501
        """
        pass

    def test_get_journey_action(self):
        """Test case for get_journey_action

        Get specific Journey Action.  # noqa: E501
        """
        pass

    def test_get_journey_action_list(self):
        """Test case for get_journey_action_list

        Get all Journey Actions.  # noqa: E501
        """
        pass

    def test_get_profile_view_templates(self):
        """Test case for get_profile_view_templates

        Get Profile View Templates  # noqa: E501
        """
        pass

    def test_get_report_by_name(self):
        """Test case for get_report_by_name

        Get Report by Name  # noqa: E501
        """
        pass

    def test_get_view_status(self):
        """Test case for get_view_status

        Get the status of a Progressive Profile View Job.  # noqa: E501
        """
        pass

    def test_post_events(self):
        """Test case for post_events

        Post Events  # noqa: E501
        """
        pass

    def test_profile_builder(self):
        """Test case for profile_builder

        A Profile is a bespoke view of a customer's journey.  # noqa: E501
        """
        pass

    def test_read_events(self):
        """Test case for read_events

        Read Events  # noqa: E501
        """
        pass

    def test_read_events_by_identity(self):
        """Test case for read_events_by_identity

        Read Events By Identity  # noqa: E501
        """
        pass

    def test_read_streams(self):
        """Test case for read_streams

        Read Streams  # noqa: E501
        """
        pass

    def test_read_streams_by_person(self):
        """Test case for read_streams_by_person

        Read Streams by Person  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
