# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.modified_cloud_event import ModifiedCloudEvent  # noqa: E501
from swagger_client.rest import ApiException


class TestModifiedCloudEvent(unittest.TestCase):
    """ModifiedCloudEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifiedCloudEvent(self):
        """Test ModifiedCloudEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.modified_cloud_event.ModifiedCloudEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
