# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.http_generic_list_object_response_journey_action import HttpGenericListObjectResponseJourneyAction  # noqa: E501
from swagger_client.rest import ApiException


class TestHttpGenericListObjectResponseJourneyAction(unittest.TestCase):
    """HttpGenericListObjectResponseJourneyAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpGenericListObjectResponseJourneyAction(self):
        """Test HttpGenericListObjectResponseJourneyAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.http_generic_list_object_response_journey_action.HttpGenericListObjectResponseJourneyAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
