# coding: utf-8

"""
    Azure Functions OpenAPI Extension

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.http_simple_message_object_response import HttpSimpleMessageObjectResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestHttpSimpleMessageObjectResponse(unittest.TestCase):
    """HttpSimpleMessageObjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpSimpleMessageObjectResponse(self):
        """Test HttpSimpleMessageObjectResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.http_simple_message_object_response.HttpSimpleMessageObjectResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
